---
- hosts: all
  become: yes
  tasks:
  - name: webserverinstallationonredhatnodes
    yum:
      name: httpd
      state: present
    when: ansible_os_family =="RedHat"
  - name: startservice
    service:
      name: httpd 
      state: started
    when: ansible_os_family =="RedHat"


     


