---
# tasks file for mytomcatinstall
 - name : install tomcat
   yum:
    name: tomcat
    state: present
   notify: servicestart

 - name: get config file
   template:
    src: template/config.j2
    dest: /usr/share/tomcat/conf/tomcat.conf

 - name: get xmlconfig file
   template:
    src: template/config.j2
    dest: /usr/share/tomcat/conf/tomcat-users.xml

 - name: get webapps
   yum:
    name: "{{ item }}" 
    state: present
   with_items:
     - tomcat-webapps
     - tomcat-admin-webapps
   notify: servicerestart
   