---
# tasks file for mytomcatdeploy
- name: delete existing war file
  file:
   path: /usr/share/tomcat/webapps/{{item}}
   state: absent
  with_items:
    - SKRlogin
    - SKRlogin.war
  when: ansible_os_family == "Debian"

- name: download war file and place in webapps
  get_url:
   url: https://s3-ap-southeast-1.amazonaws.com/jenkinsvrk/jenkins.war
   dest: /usr/share/tomcat/webapps/
   force_basic_auth: yes
  notify: servicerestart
  when: ansible_os_family == "Debian"